/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CategoryCatRouteImport } from './routes/category/$cat'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as ProgressTokenRouteImport } from './routes/progress.$token'
import { Route as ApiActivateSessionRouteImport } from './routes/api/activate/session'
import { Route as ApiAdminDeliveryRouteImport } from './routes/api/admin/delivery'
import { Route as ApiAdminProjectsRouteImport } from './routes/api/admin/projects'
import { Route as ApiAdminSimulateRouteImport } from './routes/api/admin/simulate'
import { Route as ApiAuthIndexRouteImport } from './routes/api/auth/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProgressTokenRouteImport } from './routes/api/progress/$token'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiWhitelistRequestRouteImport } from './routes/api/whitelist/request'
import { Route as ApiWhitelistVerifyRouteImport } from './routes/api/whitelist/verify'
import { Route as ApiAdminWhitelistExportRouteImport } from './routes/api/admin/whitelist/export'
import { Route as ApiAdminWhitelistImportRouteImport } from './routes/api/admin/whitelist/import'
import { Route as ApiAdminWhitelistJsonRouteImport } from './routes/api/admin/whitelist/json'
import { Route as ApiAdminWhitelistMachinesRouteImport } from './routes/api/admin/whitelist/machines'
import { Route as ApiAdminWhitelistMachinesIdRouteImport } from './routes/api/admin/whitelist/machines.$id'
import { Route as ApiAdminWhitelistMachinesIdRegenerateTokenRouteImport } from './routes/api/admin/whitelist/machines.$id.regenerate-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCatRoute = CategoryCatRouteImport.update({
  id: '/category/$cat',
  path: '/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressTokenRoute = ProgressTokenRouteImport.update({
  id: '/progress/$token',
  path: '/progress/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivateSessionRoute = ApiActivateSessionRouteImport.update({
  id: '/api/activate/session',
  path: '/api/activate/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeliveryRoute = ApiAdminDeliveryRouteImport.update({
  id: '/api/admin/delivery',
  path: '/api/admin/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProjectsRoute = ApiAdminProjectsRouteImport.update({
  id: '/api/admin/projects',
  path: '/api/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSimulateRoute = ApiAdminSimulateRouteImport.update({
  id: '/api/admin/simulate',
  path: '/api/admin/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthIndexRoute = ApiAuthIndexRouteImport.update({
  id: '/api/auth/',
  path: '/api/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressTokenRoute = ApiProgressTokenRouteImport.update({
  id: '/api/progress/$token',
  path: '/api/progress/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhitelistRequestRoute = ApiWhitelistRequestRouteImport.update({
  id: '/api/whitelist/request',
  path: '/api/whitelist/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhitelistVerifyRoute = ApiWhitelistVerifyRouteImport.update({
  id: '/api/whitelist/verify',
  path: '/api/whitelist/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWhitelistExportRoute = ApiAdminWhitelistExportRouteImport.update({
  id: '/api/admin/whitelist/export',
  path: '/api/admin/whitelist/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWhitelistImportRoute = ApiAdminWhitelistImportRouteImport.update({
  id: '/api/admin/whitelist/import',
  path: '/api/admin/whitelist/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWhitelistJsonRoute = ApiAdminWhitelistJsonRouteImport.update({
  id: '/api/admin/whitelist/json',
  path: '/api/admin/whitelist/json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWhitelistMachinesRoute =
  ApiAdminWhitelistMachinesRouteImport.update({
    id: '/api/admin/whitelist/machines',
    path: '/api/admin/whitelist/machines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWhitelistMachinesIdRoute =
  ApiAdminWhitelistMachinesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminWhitelistMachinesRoute,
  } as any)
const ApiAdminWhitelistMachinesIdRegenerateTokenRoute =
  ApiAdminWhitelistMachinesIdRegenerateTokenRouteImport.update({
    id: '/regenerate-token',
    path: '/regenerate-token',
    getParentRoute: () => ApiAdminWhitelistMachinesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/research': typeof ResearchRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$cat': typeof CategoryCatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/progress/$token': typeof ProgressTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/api/activate/session': typeof ApiActivateSessionRoute
  '/api/admin/delivery': typeof ApiAdminDeliveryRoute
  '/api/admin/projects': typeof ApiAdminProjectsRoute
  '/api/admin/simulate': typeof ApiAdminSimulateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/progress/$token': typeof ApiProgressTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whitelist/request': typeof ApiWhitelistRequestRoute
  '/api/whitelist/verify': typeof ApiWhitelistVerifyRoute
  '/api/auth/': typeof ApiAuthIndexRoute
  '/api/admin/whitelist/export': typeof ApiAdminWhitelistExportRoute
  '/api/admin/whitelist/import': typeof ApiAdminWhitelistImportRoute
  '/api/admin/whitelist/json': typeof ApiAdminWhitelistJsonRoute
  '/api/admin/whitelist/machines': typeof ApiAdminWhitelistMachinesRouteWithChildren
  '/api/admin/whitelist/machines/$id': typeof ApiAdminWhitelistMachinesIdRouteWithChildren
  '/api/admin/whitelist/machines/$id/regenerate-token': typeof ApiAdminWhitelistMachinesIdRegenerateTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/research': typeof ResearchRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$cat': typeof CategoryCatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/progress/$token': typeof ProgressTokenRoute
  '/blog': typeof BlogIndexRoute
  '/api/activate/session': typeof ApiActivateSessionRoute
  '/api/admin/delivery': typeof ApiAdminDeliveryRoute
  '/api/admin/projects': typeof ApiAdminProjectsRoute
  '/api/admin/simulate': typeof ApiAdminSimulateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/progress/$token': typeof ApiProgressTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whitelist/request': typeof ApiWhitelistRequestRoute
  '/api/whitelist/verify': typeof ApiWhitelistVerifyRoute
  '/api/auth': typeof ApiAuthIndexRoute
  '/api/admin/whitelist/export': typeof ApiAdminWhitelistExportRoute
  '/api/admin/whitelist/import': typeof ApiAdminWhitelistImportRoute
  '/api/admin/whitelist/json': typeof ApiAdminWhitelistJsonRoute
  '/api/admin/whitelist/machines': typeof ApiAdminWhitelistMachinesRouteWithChildren
  '/api/admin/whitelist/machines/$id': typeof ApiAdminWhitelistMachinesIdRouteWithChildren
  '/api/admin/whitelist/machines/$id/regenerate-token': typeof ApiAdminWhitelistMachinesIdRegenerateTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/internships': typeof InternshipsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/research': typeof ResearchRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$cat': typeof CategoryCatRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/progress/$token': typeof ProgressTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/api/activate/session': typeof ApiActivateSessionRoute
  '/api/admin/delivery': typeof ApiAdminDeliveryRoute
  '/api/admin/projects': typeof ApiAdminProjectsRoute
  '/api/admin/simulate': typeof ApiAdminSimulateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/progress/$token': typeof ApiProgressTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whitelist/request': typeof ApiWhitelistRequestRoute
  '/api/whitelist/verify': typeof ApiWhitelistVerifyRoute
  '/api/auth/': typeof ApiAuthIndexRoute
  '/api/admin/whitelist/export': typeof ApiAdminWhitelistExportRoute
  '/api/admin/whitelist/import': typeof ApiAdminWhitelistImportRoute
  '/api/admin/whitelist/json': typeof ApiAdminWhitelistJsonRoute
  '/api/admin/whitelist/machines': typeof ApiAdminWhitelistMachinesRouteWithChildren
  '/api/admin/whitelist/machines/$id': typeof ApiAdminWhitelistMachinesIdRouteWithChildren
  '/api/admin/whitelist/machines/$id/regenerate-token': typeof ApiAdminWhitelistMachinesIdRegenerateTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/admin'
    | '/demo'
    | '/internships'
    | '/login'
    | '/orders'
    | '/research'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/blog/$slug'
    | '/category/$cat'
    | '/products/$slug'
    | '/progress/$token'
    | '/blog/'
    | '/api/activate/session'
    | '/api/admin/delivery'
    | '/api/admin/projects'
    | '/api/admin/simulate'
    | '/api/auth/$'
    | '/api/progress/$token'
    | '/api/stripe/webhook'
    | '/api/whitelist/request'
    | '/api/whitelist/verify'
    | '/api/auth/'
    | '/api/admin/whitelist/export'
    | '/api/admin/whitelist/import'
    | '/api/admin/whitelist/json'
    | '/api/admin/whitelist/machines'
    | '/api/admin/whitelist/machines/$id'
    | '/api/admin/whitelist/machines/$id/regenerate-token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/admin'
    | '/demo'
    | '/internships'
    | '/login'
    | '/orders'
    | '/research'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/blog/$slug'
    | '/category/$cat'
    | '/products/$slug'
    | '/progress/$token'
    | '/blog'
    | '/api/activate/session'
    | '/api/admin/delivery'
    | '/api/admin/projects'
    | '/api/admin/simulate'
    | '/api/auth/$'
    | '/api/progress/$token'
    | '/api/stripe/webhook'
    | '/api/whitelist/request'
    | '/api/whitelist/verify'
    | '/api/auth'
    | '/api/admin/whitelist/export'
    | '/api/admin/whitelist/import'
    | '/api/admin/whitelist/json'
    | '/api/admin/whitelist/machines'
    | '/api/admin/whitelist/machines/$id'
    | '/api/admin/whitelist/machines/$id/regenerate-token'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/admin'
    | '/demo'
    | '/internships'
    | '/login'
    | '/orders'
    | '/research'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/blog/$slug'
    | '/category/$cat'
    | '/products/$slug'
    | '/progress/$token'
    | '/blog/'
    | '/api/activate/session'
    | '/api/admin/delivery'
    | '/api/admin/projects'
    | '/api/admin/simulate'
    | '/api/auth/$'
    | '/api/progress/$token'
    | '/api/stripe/webhook'
    | '/api/whitelist/request'
    | '/api/whitelist/verify'
    | '/api/auth/'
    | '/api/admin/whitelist/export'
    | '/api/admin/whitelist/import'
    | '/api/admin/whitelist/json'
    | '/api/admin/whitelist/machines'
    | '/api/admin/whitelist/machines/$id'
    | '/api/admin/whitelist/machines/$id/regenerate-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRoute
  DemoRoute: typeof DemoRoute
  InternshipsRoute: typeof InternshipsRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ResearchRoute: typeof ResearchRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoryCatRoute: typeof CategoryCatRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProgressTokenRoute: typeof ProgressTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiActivateSessionRoute: typeof ApiActivateSessionRoute
  ApiAdminDeliveryRoute: typeof ApiAdminDeliveryRoute
  ApiAdminProjectsRoute: typeof ApiAdminProjectsRoute
  ApiAdminSimulateRoute: typeof ApiAdminSimulateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProgressTokenRoute: typeof ApiProgressTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWhitelistRequestRoute: typeof ApiWhitelistRequestRoute
  ApiWhitelistVerifyRoute: typeof ApiWhitelistVerifyRoute
  ApiAuthIndexRoute: typeof ApiAuthIndexRoute
  ApiAdminWhitelistExportRoute: typeof ApiAdminWhitelistExportRoute
  ApiAdminWhitelistImportRoute: typeof ApiAdminWhitelistImportRoute
  ApiAdminWhitelistJsonRoute: typeof ApiAdminWhitelistJsonRoute
  ApiAdminWhitelistMachinesRoute: typeof ApiAdminWhitelistMachinesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$cat': {
      id: '/category/$cat'
      path: '/category/$cat'
      fullPath: '/category/$cat'
      preLoaderRoute: typeof CategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/$token': {
      id: '/progress/$token'
      path: '/progress/$token'
      fullPath: '/progress/$token'
      preLoaderRoute: typeof ProgressTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activate/session': {
      id: '/api/activate/session'
      path: '/api/activate/session'
      fullPath: '/api/activate/session'
      preLoaderRoute: typeof ApiActivateSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delivery': {
      id: '/api/admin/delivery'
      path: '/api/admin/delivery'
      fullPath: '/api/admin/delivery'
      preLoaderRoute: typeof ApiAdminDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/projects': {
      id: '/api/admin/projects'
      path: '/api/admin/projects'
      fullPath: '/api/admin/projects'
      preLoaderRoute: typeof ApiAdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/simulate': {
      id: '/api/admin/simulate'
      path: '/api/admin/simulate'
      fullPath: '/api/admin/simulate'
      preLoaderRoute: typeof ApiAdminSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/': {
      id: '/api/auth/'
      path: '/api/auth'
      fullPath: '/api/auth/'
      preLoaderRoute: typeof ApiAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/$token': {
      id: '/api/progress/$token'
      path: '/api/progress/$token'
      fullPath: '/api/progress/$token'
      preLoaderRoute: typeof ApiProgressTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whitelist/request': {
      id: '/api/whitelist/request'
      path: '/api/whitelist/request'
      fullPath: '/api/whitelist/request'
      preLoaderRoute: typeof ApiWhitelistRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whitelist/verify': {
      id: '/api/whitelist/verify'
      path: '/api/whitelist/verify'
      fullPath: '/api/whitelist/verify'
      preLoaderRoute: typeof ApiWhitelistVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whitelist/export': {
      id: '/api/admin/whitelist/export'
      path: '/api/admin/whitelist/export'
      fullPath: '/api/admin/whitelist/export'
      preLoaderRoute: typeof ApiAdminWhitelistExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whitelist/import': {
      id: '/api/admin/whitelist/import'
      path: '/api/admin/whitelist/import'
      fullPath: '/api/admin/whitelist/import'
      preLoaderRoute: typeof ApiAdminWhitelistImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whitelist/json': {
      id: '/api/admin/whitelist/json'
      path: '/api/admin/whitelist/json'
      fullPath: '/api/admin/whitelist/json'
      preLoaderRoute: typeof ApiAdminWhitelistJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whitelist/machines': {
      id: '/api/admin/whitelist/machines'
      path: '/api/admin/whitelist/machines'
      fullPath: '/api/admin/whitelist/machines'
      preLoaderRoute: typeof ApiAdminWhitelistMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whitelist/machines/$id': {
      id: '/api/admin/whitelist/machines/$id'
      path: '/$id'
      fullPath: '/api/admin/whitelist/machines/$id'
      preLoaderRoute: typeof ApiAdminWhitelistMachinesIdRouteImport
      parentRoute: typeof ApiAdminWhitelistMachinesRoute
    }
    '/api/admin/whitelist/machines/$id/regenerate-token': {
      id: '/api/admin/whitelist/machines/$id/regenerate-token'
      path: '/regenerate-token'
      fullPath: '/api/admin/whitelist/machines/$id/regenerate-token'
      preLoaderRoute: typeof ApiAdminWhitelistMachinesIdRegenerateTokenRouteImport
      parentRoute: typeof ApiAdminWhitelistMachinesIdRoute
    }
  }
}

interface ApiAdminWhitelistMachinesIdRouteChildren {
  ApiAdminWhitelistMachinesIdRegenerateTokenRoute: typeof ApiAdminWhitelistMachinesIdRegenerateTokenRoute
}

const ApiAdminWhitelistMachinesIdRouteChildren: ApiAdminWhitelistMachinesIdRouteChildren =
  {
    ApiAdminWhitelistMachinesIdRegenerateTokenRoute:
      ApiAdminWhitelistMachinesIdRegenerateTokenRoute,
  }

const ApiAdminWhitelistMachinesIdRouteWithChildren =
  ApiAdminWhitelistMachinesIdRoute._addFileChildren(
    ApiAdminWhitelistMachinesIdRouteChildren,
  )

interface ApiAdminWhitelistMachinesRouteChildren {
  ApiAdminWhitelistMachinesIdRoute: typeof ApiAdminWhitelistMachinesIdRouteWithChildren
}

const ApiAdminWhitelistMachinesRouteChildren: ApiAdminWhitelistMachinesRouteChildren =
  {
    ApiAdminWhitelistMachinesIdRoute:
      ApiAdminWhitelistMachinesIdRouteWithChildren,
  }

const ApiAdminWhitelistMachinesRouteWithChildren =
  ApiAdminWhitelistMachinesRoute._addFileChildren(
    ApiAdminWhitelistMachinesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRoute,
  DemoRoute: DemoRoute,
  InternshipsRoute: InternshipsRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ResearchRoute: ResearchRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoryCatRoute: CategoryCatRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProgressTokenRoute: ProgressTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiActivateSessionRoute: ApiActivateSessionRoute,
  ApiAdminDeliveryRoute: ApiAdminDeliveryRoute,
  ApiAdminProjectsRoute: ApiAdminProjectsRoute,
  ApiAdminSimulateRoute: ApiAdminSimulateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProgressTokenRoute: ApiProgressTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWhitelistRequestRoute: ApiWhitelistRequestRoute,
  ApiWhitelistVerifyRoute: ApiWhitelistVerifyRoute,
  ApiAuthIndexRoute: ApiAuthIndexRoute,
  ApiAdminWhitelistExportRoute: ApiAdminWhitelistExportRoute,
  ApiAdminWhitelistImportRoute: ApiAdminWhitelistImportRoute,
  ApiAdminWhitelistJsonRoute: ApiAdminWhitelistJsonRoute,
  ApiAdminWhitelistMachinesRoute: ApiAdminWhitelistMachinesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
